spring:
  flyway:
    enabled: true
    default-schema: public
    target: latest
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/${DB_NAME}

server:
  port: 8081
